### ISSUE TITLE
what command should I input in powershell to redirect the inputstream to a program?

### ISSUE THREAD

**Issue by jameslahm** [UndyingSoul/Hello-World#360]
I have known that >> can redirect the outputstream, but when  I use << , it warns that it's a future command. for example, how can I achieve function such as  “./main.exe  < input.txt”. main.exe is a C++ program.; input.txt is the file to input.

**Comment by UndyingSoul** [comment]
I'm assuming that you are wanting to pass "input.txt" into the program "main.exe" and that "main.exe processes the file and outputs a result. If that is the case, 
Here is a source file that you should be using if you want to pass in an input file.
https://gist.github.com/UndyingSoul/8c313687b6bd32090598ed86a3888d1a
To call this program all you have to do is run a command line (cmd prompt, PowerShell, or bash) and do the following: executable.exe inputFile.txt
Of course, you are replacing executable with your program and inputFile.txt with your input file (both static and dynamic filenames are supported) Note: if your path or file name has a space in it, use double quotes around it.
I'm going to be closing this issue because it is not related to my repo. If you need further help, just send me a message.
